name: Deploy - GCP - Repository

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build Python package
        run: python setup.py sdist bdist_wheel

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.PROJECT_ID }}
          workload_identity_provider: ${{ vars.SECRET_WIP_NAME }}
          service_account: ${{ vars.PROVIDER_SA_EMAIL }}

      - name: Upload package to Google Artifact Registry
        env:
          TWINE_USERNAME: 'oauth2accesstoken'
          TWINE_PASSWORD: $(gcloud auth print-access-token)
          TWINE_REPOSITORY_URL: https://europe-west1-python.pkg.dev/soral-app-dev/pypi-custom
        run: twine upload --non-interactive dist/*
