name: Deploy - GCP - Repository

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prd
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build Python package
        run: python setup.py sdist bdist_wheel

      - name: Check if tag matches version
        run: |
          DIST_PKG_FILE=$(ls dist/*-${GITHUB_REF#refs/tags/}*.tar.gz)
          if [ -z "$DIST_PKG_FILE" ]; then
            echo "No distribution package found for tag ${GITHUB_REF#refs/tags/}"
            exit 1
          fi
          
          VERSION=$(echo ${DIST_PKG_FILE#dist/*} | cut -d. -f1-3 | rev | cut -d- -f1 | rev)
          TAG_NAME=${GITHUB_REF#refs/tags/}
          
          if [ "$VERSION" != "$TAG_NAME" ]; then
            echo "Version extracted from package filename ($VERSION) does not match the tag name ($TAG_NAME)"
            exit 1
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.PROJECT_ID }}
          workload_identity_provider: ${{ vars.SECRET_WIP_NAME }}
          service_account: ${{ vars.PROVIDER_SA_EMAIL }}


